nexus:
  image: "sonatype/nexus3"
  ports:
  -  "${PORT}:8081"
  labels:
    io.rancher.sidekicks: nexus-data
    io.rancher.container.hostname_override: container_name
  volumes_from:
    -  nexus-data
  entrypoint: ["ls", "-la", "/"]
nexus-data:
  image: "sonatype/nexus3"
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["echo", "data only"]
